/*
 * This Java source file was generated by the Gradle 'init' task.
 */

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class ExampleTest {
    @Test void testSomeLibraryMethod() {
        Example classUnderTest = new Example();
        assertTrue(classUnderTest.someLibraryMethod(), "someLibraryMethod should return 'true'");
    }
}
// mock - sprawda czy zostaly wywolane tylko przewidziane metody w dowolnej kolejnosci
// strictmock - zapisuje kolejnosc wywolanych metod
// nicemock - nie wywoluje AssertionError dla niespodziewanych metod
// partialmock - mockujemy tylko poszczegolne metody
